on:
  push

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: x64
            arch: x64

    runs-on: [self-hosted, "${{ matrix.runner }}"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_options: --no-daemon
          extra_nix_config: experimental-features = nix-command flakes

      - name: Test
        shell: bash
        run: nix-shell --run 'make test'
